window.BIBLICAL_NAMES = [
  {name: "Adam", hebrew: "אדם"},
  {name: "Eve", hebrew: "חוה"},
  {name: "Cain", hebrew: "קין"},
  {name: "Abel", hebrew: "הבל"},
  {name: "Seth", hebrew: "שת"},
  {name: "Enoch", hebrew: "חנוך"},
  {name: "Methuselah", hebrew: "מתושלח"},
  {name: "Noah", hebrew: "נח"},
  {name: "Shem", hebrew: "שם"},
  {name: "Ham", hebrew: "חם"},
  {name: "Japheth", hebrew: "יפת"},
  {name: "Abraham", hebrew: "אברהם"},
  {name: "Sarah", hebrew: "שרה"},
  {name: "Hagar", hebrew: "הגר"},
  {name: "Keturah", hebrew: "קטורה"},
  {name: "Ishmael", hebrew: "ישמעאל"},
  {name: "Isaac", hebrew: "יצחק"},
  {name: "Rebekah", hebrew: "רבקה"},
  {name: "Jacob", hebrew: "יעקב"},
  {name: "Esau", hebrew: "עשו"},
  {name: "Rachel", hebrew: "רחל"},
  {name: "Leah", hebrew: "לאה"},
  {name: "Joseph", hebrew: "יוסף"},
  {name: "Benjamin", hebrew: "בנימין"},
  {name: "Dinah", hebrew: "דינה"},
  {name: "Moses", hebrew: "משה"},
  {name: "Aaron", hebrew: "אהרן"},
  {name: "Miriam", hebrew: "מרים"},
  {name: "Joshua", hebrew: "יהושע"},
  {name: "Caleb", hebrew: "כלב"},
  {name: "Othniel", hebrew: "עתניאל"},
  {name: "Ehud", hebrew: "אהוד"},
  {name: "Shamgar", hebrew: "שַׁמְגַּר"},
  {name: "Deborah", hebrew: "דבורה"},
  {name: "Gideon", hebrew: "גדעון"},
  {name: "Tola", hebrew: "תולע"},
  {name: "Jair", hebrew: "יאיר"},
  {name: "Jephthah", hebrew: "יפתח"},
  {name: "Ibzan", hebrew: "אבצן"},
  {name: "Elon", hebrew: "אלון"},
  {name: "Abdon", hebrew: "עבדון"},
  {name: "Samson", hebrew: "שמשון"},
  {name: "Eli", hebrew: "עלי"},
  {name: "Samuel", hebrew: "שמואל"},
  {name: "Elijah", hebrew: "אליהו"},
  {name: "Elisha", hebrew: "אלישע"},
  {name: "Isaiah", hebrew: "ישעיהו"},
  {name: "Jeremiah", hebrew: "ירמיהו"},
  {name: "Ezekiel", hebrew: "יחזקאל"},
  {name: "Daniel", hebrew: "דניאל"},
  {name: "Hosea", hebrew: "הושע"},
  {name: "Joel", hebrew: "יואל"},
  {name: "Amos", hebrew: "עמוס"},
  {name: "Obadiah", hebrew: "עבדיה"},
  {name: "Jonah", hebrew: "יונה"},
  {name: "Micah", hebrew: "מיכה"},
  {name: "Nahum", hebrew: "נחום"},
  {name: "Habakkuk", hebrew: "חבקוק"},
  {name: "Zephaniah", hebrew: "צפניה"},
  {name: "Haggai", hebrew: "חגי"},
  {name: "Zechariah", hebrew: "זכריה"},
  {name: "Malachi", hebrew: "מלאכי"},
  {name: "Saul", hebrew: "שאול"},
  {name: "David", hebrew: "דוד"},
  {name: "Jonathan", hebrew: "יהונתן"},
  {name: "Solomon", hebrew: "שלמה"},
  {name: "Rehoboam", hebrew: "רחבעם"},
  {name: "Abijah", hebrew: "אביה"},
  {name: "Asa", hebrew: "אסא"},
  {name: "Jehoshaphat", hebrew: "יהושפט"},
  {name: "Jehoram of Judah", hebrew: "יהורם"},
  {name: "Ahaziah of Judah", hebrew: "אחזיה"},
  {name: "Athaliah", hebrew: "עתליה"},
  {name: "Joash of Judah", hebrew: "יואש"},
  {name: "Amaziah", hebrew: "אמציה"},
  {name: "Uzziah", hebrew: "עזיהו"},
  {name: "Jotham", hebrew: "יותם"},
  {name: "Ahaz", hebrew: "אחז"},
  {name: "Hezekiah", hebrew: "חזקיהו"},
  {name: "Manasseh", hebrew: "מנשה"},
  {name: "Amon", hebrew: "אמון"},
  {name: "Josiah", hebrew: "יאשיהו"},
  {name: "Jehoahaz", hebrew: "יהואחז"},
  {name: "Jehoiakim", hebrew: "יהויקים"},
  {name: "Jehoiachin", hebrew: "יהויכין"},
  {name: "Zedekiah", hebrew: "צדקיהו"},
  {name: "Jeroboam I", hebrew: "ירבעם"},
  {name: "Nadab", hebrew: "נדב"},
  {name: "Baasha", hebrew: "בעשא"},
  {name: "Elah", hebrew: "אלה"},
  {name: "Zimri", hebrew: "זמרי"},
  {name: "Omri", hebrew: "עמרי"},
  {name: "Ahab", hebrew: "אחאב"},
  {name: "Ahaziah of Israel", hebrew: "אחזיהו"},
  {name: "Joram of Israel", hebrew: "יורם"},
  {name: "Jehu", hebrew: "יהוא"},
  {name: "Jehoahaz of Israel", hebrew: "יהואחז"},
  {name: "Jehoash of Israel", hebrew: "יהואש"},
  {name: "Jeroboam II", hebrew: "ירבעם"},
  {name: "Zechariah son of Jeroboam", hebrew: "זכריה"},
  {name: "Shallum", hebrew: "שלום"},
  {name: "Menahem", hebrew: "מנחם"},
  {name: "Pekahiah", hebrew: "פקחיה"},
  {name: "Pekah", hebrew: "פקח"},
  {name: "Hoshea", hebrew: "הושע"},
  {name: "Pharaoh", hebrew: "פרעה"},
  {name: "Shishak", hebrew: "שישק"},
  {name: "Sennacherib", hebrew: "סנחריב"},
  {name: "Tiglath-Pileser", hebrew: "תגלת פלאסר"},
  {name: "Shalmaneser", hebrew: "שלמנאסר"},
  {name: "Esarhaddon", hebrew: "אסרחדון"},
  {name: "Nebuchadnezzar", hebrew: "נבוכדנצר"},
  {name: "Evil-merodach", hebrew: "אויל מרודך"},
  {name: "Belshazzar", hebrew: "בלשאצר"},
  {name: "Darius the Mede", hebrew: "דריוש המדי"},
  {name: "Cyrus", hebrew: "כורש"},
  {name: "Darius I", hebrew: "דריוש"},
  {name: "Xerxes (Ahasuerus)", hebrew: "אחשורוש"},
  {name: "Artaxerxes", hebrew: "ארתחששתא"},
  {name: "Abigail", hebrew: "אביגיל"},
  {name: "Michal", hebrew: "מיכל"},
  {name: "Tamar wife of Judah", hebrew: "תמר"},
  {name: "Tamar daughter of David", hebrew: "תמר"},
  {name: "Rizpah", hebrew: "רץפה"},
  {name: "Huldah", hebrew: "חולדה"},
  {name: "Jael", hebrew: "יעל"},
  {name: "Shiphrah", hebrew: "שפרה"},
  {name: "Puah", hebrew: "פועה"},
  {name: "Zipporah", hebrew: "ציפורה"},
  {name: "Zadok", hebrew: "צדוק"},
  {name: "Abiathar", hebrew: "אביתר"},
  {name: "Hilkiah", hebrew: "חלקיהו"},
  {name: "Jehoiada", hebrew: "יהוידע"},
  {name: "Ezra", hebrew: "עזרא"},
  {name: "Nehemiah", hebrew: "נחמיה"},
  {name: "Zerubbabel", hebrew: "זרובבל"},
  {name: "Joshua son of Jehozadak", hebrew: "יהושע בן יהוצדק"},
  {name: "Eliashib", hebrew: "אלישיב"},
  {name: "Jesus", hebrew: "ישוע"},
  {name: "Peter", hebrew: "פטרוס"},
  {name: "Andrew", hebrew: "אנדריאס"},
  {name: "James son of Zebedee", hebrew: "יעקב בן זבדי"},
  {name: "John son of Zebedee", hebrew: "יוחנן בן זבדי"},
  {name: "Philip", hebrew: "פיליפוס"},
  {name: "Bartholomew", hebrew: "ברתולומאיוס"},
  {name: "Thomas", hebrew: "תומאס"},
  {name: "Matthew", hebrew: "מתתיהו"},
  {name: "James son of Alphaeus", hebrew: "יעקב בן חלפי"},
  {name: "Thaddaeus", hebrew: "תדיוס"},
  {name: "Simon the Zealot", hebrew: "שמעון הקנאי"},
  {name: "Judas Iscariot", hebrew: "יהודה איש קריות"},
  {name: "Matthias", hebrew: "מתיאס"},
  {name: "Paul", hebrew: "פאולוס"},
  {name: "Barnabas", hebrew: "ברנבא"},
  {name: "Silas", hebrew: "סילאס"},
  {name: "Timothy", hebrew: "טימותיוס"},
  {name: "Titus", hebrew: "טיטוס"},
  {name: "Luke", hebrew: "לוקס"},
  {name: "Mark", hebrew: "מרקוס"},
  {name: "Apollos", hebrew: "אפולוס"},
  {name: "Aquila", hebrew: "אקילה"},
  {name: "Priscilla", hebrew: "פריסילה"},
  {name: "Phoebe", hebrew: "פיבי"},
  {name: "Lydia", hebrew: "לידיה"},
  {name: "Cornelius", hebrew: "קורנליוס"},
  {name: "Stephen", hebrew: "סטפנוס"},
  {name: "Philip the Evangelist", hebrew: "פיליפוס המְבַשֵּׂר"},
  {name: "Simeon Niger", hebrew: "שמעון הניגרי"},
  {name: "Manaen", hebrew: "מנאחם"},
  {name: "Crispus", hebrew: "קריספוס"},
  {name: "Sosthenes", hebrew: "סוסתנס"},
  {name: "Gaius", hebrew: "גאיוס"},
  {name: "Tychicus", hebrew: "טיכיקוס"},
  {name: "Onesimus", hebrew: "אנסימוס"},
  {name: "Epaphroditus", hebrew: "אפפרודיטוס"},
  {name: "Epaphras", hebrew: "אפפרס"},
  {name: "Archippus", hebrew: "ארכיפוס"},
  {name: "Demas", hebrew: "דימס"},
  {name: "Aristarchus", hebrew: "אריסטארכוס"},
  {name: "Jason", hebrew: "יסון"},
  {name: "Erastus", hebrew: "ארסטוס"},
  {name: "Chloe", hebrew: "קלואי"},
  {name: "Nympha", hebrew: "ניםפה"},
  {name: "Euodia", hebrew: "אואודיה"},
  {name: "Syntyche", hebrew: "סונטיכה"},
  {name: "Lois", hebrew: "לואיס"},
  {name: "Eunice", hebrew: "יוניס"},
  {name: "Apelles", hebrew: "אפלתס"},
  {name: "Rufus", hebrew: "רופוס"},
  {name: "Urbanus", hebrew: "אורבנוס"},
  {name: "Tryphena", hebrew: "טריפנה"},
  {name: "Tryphosa", hebrew: "טריפוסה"},
  {name: "Persis", hebrew: "פרסיס"},
  {name: "Asyncritus", hebrew: "אסינקריטוס"},
  {name: "Phlegon", hebrew: "פלגון"},
  {name: "Hermes", hebrew: "הרמס"},
  {name: "Patrobas", hebrew: "פטרובס"},
  {name: "Hermas", hebrew: "הרמס"},
  {name: "Philologus", hebrew: "פילולוגוס"},
  {name: "Julia", hebrew: "יוליה"},
  {name: "Nereus", hebrew: "נריאוס"},
  {name: "Olympas", hebrew: "אולימפס"},
  {name: "Tertius", hebrew: "טרטיאוס"},
  {name: "Quartus", hebrew: "קוורטוס"},
  {name: "Sopater", hebrew: "סופטר"},
  {name: "Secundus", hebrew: "סקונדוס"},
  {name: "Trophimus", hebrew: "טרופימוס"},
  {name: "Eutychus", hebrew: "אויטיכוס"},
  {name: "Agabus", hebrew: "אגבוס"},
  {name: "Ananias of Damascus", hebrew: "חנניה"},
  {name: "Sapphira", hebrew: "ספירה"},
  {name: "Gamaliel", hebrew: "גמליאל"},
  {name: "Theophilus", hebrew: "תאופילוס"},
  {name: "Elymas (Bar-Jesus)", hebrew: "אלימס"},
  {name: "Sergius Paulus", hebrew: "סרגיוס פאולוס"},
  {name: "Felix", hebrew: "פליקס"},
  {name: "Festus", hebrew: "פסטוס"},
  {name: "Agrippa II", hebrew: "אגריפס השני"},
  {name: "Bernice", hebrew: "ברניקה"},
  {name: "Drusilla", hebrew: "דרוסילה"},
  {name: "Herod Antipas", hebrew: "הורדוס אנטיפס"},
  {name: "Herod Agrippa I", hebrew: "הורדוס אגריפס הראשון"},
  {name: "Herod Agrippa II", hebrew: "הורדוס אגריפס השני"},
  {name: "Michael", hebrew: "מיכאל"},
  {name: "Gabriel", hebrew: "גבריאל"},
  {name: "Raphael", hebrew: "רפאל"},
  {name: "Uriel", hebrew: "אוריאל"},
  {name: "Satan", hebrew: "שטן"},
  {name: "Lucifer", hebrew: "לוציפר"},
  {name: "Beelzebub", hebrew: "בעל זבוב"},
  {name: "Belial", hebrew: "בליעל"},
  {name: "Abaddon", hebrew: "אבדון"},
  {name: "Apollyon", hebrew: "אפוליון"},
  {name: "Asmodeus", hebrew: "אשמדאי"},
  {name: "Molech", hebrew: "מולך"},
  {name: "Baal", hebrew: "בעל"},
  {name: "Ashtoreth", hebrew: "עשתרת"},
  {name: "Chemosh", hebrew: "כמוש"},
  {name: "Dagon", hebrew: "דגון"},
  {name: "Tammuz", hebrew: "תמוז"},
  {name: "Leviathan", hebrew: "לויתן"},
  {name: "Behemoth", hebrew: "בהמות"},
  {name: "Dragon", hebrew: "דרקון"},
  {name: "Rahab", hebrew: "רהב"},
  {name: "Seraphim", hebrew: "שרפים"},
  {name: "Cherubim", hebrew: "כרובים"},
  {name: "Nephilim", hebrew: "נפילים"},
  {name: "Jerusalem", hebrew: "ירושלים"},
  {name: "Zion", hebrew: "ציון"},
  {name: "Bethlehem", hebrew: "בית לחם"},
  {name: "Nazareth", hebrew: "נצרת"},
  {name: "Capernaum", hebrew: "כפר נחום"},
  {name: "Bethany", hebrew: "בית עניה"},
  {name: "Bethsaida", hebrew: "בית צידה"},
  {name: "Jericho", hebrew: "יריחו"},
  {name: "Cana", hebrew: "קנה"},
  {name: "Nain", hebrew: "נאין"},
  {name: "Emmaus", hebrew: "עמאוס"},
  {name: "Sychar", hebrew: "שכם"},
  {name: "Samaria", hebrew: "שומרון"},
  {name: "Judea", hebrew: "יהודה"},
  {name: "Galilee", hebrew: "גליל"},
  {name: "Perea", hebrew: "פראיה"},
  {name: "Decapolis", hebrew: "דקאפוליס"},
  {name: "Gennesaret", hebrew: "גינוסר"},
  {name: "Mount of Olives", hebrew: "הר הזיתים"},
  {name: "Mount Carmel", hebrew: "הר כרמל"},
  {name: "Mount Sinai", hebrew: "הר סיני"},
  {name: "Mount Zion", hebrew: "הר ציון"},
  {name: "Mount Ararat", hebrew: "הר אררט"},
  {name: "Mount Moriah", hebrew: "הר המוריה"},
  {name: "Golgotha", hebrew: "גולגלתא"},
  {name: "Gethsemane", hebrew: "גת שמנים"},
  {name: "Kidron Valley", hebrew: "נחל קדרון"},
  {name: "Valley of Hinnom", hebrew: "גיא בן הנום"},
  {name: "Jordan River", hebrew: "נהר הירדן"},
  {name: "Red Sea", hebrew: "ים סוף"},
  {name: "Dead Sea", hebrew: "ים המלח"},
  {name: "Sea of Galilee", hebrew: "ים כנרת"},
  {name: "Euphrates", hebrew: "נהר פרת"},
  {name: "Tigris", hebrew: "נהר חדקל"},
  {name: "Nile", hebrew: "נהר הנילוס"},
  {name: "Shiloh", hebrew: "שילה"},
  {name: "Bethel", hebrew: "בית אל"},
  {name: "Ai", hebrew: "עי"},
  {name: "Shechem", hebrew: "שכם"},
  {name: "Hebron", hebrew: "חברון"},
  {name: "Beersheba", hebrew: "באר שבע"},
  {name: "Megiddo", hebrew: "מגידו"},
  {name: "Jezreel", hebrew: "יזרעאל"},
  {name: "Endor", hebrew: "עין דור"},
  {name: "Engedi", hebrew: "עין גדי"},
  {name: "Ashkelon", hebrew: "אשקלון"},
  {name: "Ashdod", hebrew: "אשדוד"},
  {name: "Gaza", hebrew: "עזה"},
  {name: "Ekron", hebrew: "עקרון"},
  {name: "Gath", hebrew: "גת"},
  {name: "Joppa", hebrew: "יפו"},
  {name: "Aphek", hebrew: "אפק"},
  {name: "Ramah", hebrew: "רמה"},
  {name: "Mizpah", hebrew: "מצפה"},
  {name: "Tyre", hebrew: "צור"},
  {name: "Sidon", hebrew: "צידון"},
  {name: "Caesarea", hebrew: "קיסריה"},
  {name: "Antioch", hebrew: "אנטיוכיה"},
  {name: "Damascus", hebrew: "דמשק"},
  {name: "Tarsus", hebrew: "תרסוס"},
  {name: "Philippi", hebrew: "פיליפי"},
  {name: "Thessalonica", hebrew: "תסלוניקה"},
  {name: "Berea", hebrew: "ברואה"},
  {name: "Athens", hebrew: "אתונה"},
  {name: "Corinth", hebrew: "קורינתוס"},
  {name: "Ephesus", hebrew: "אפסוס"},
  {name: "Colossae", hebrew: "קולוסאי"},
  {name: "Laodicea", hebrew: "לאודיקיה"},
  {name: "Smyrna", hebrew: "סמירנה"},
  {name: "Pergamum", hebrew: "פרגמון"},
  {name: "Thyatira", hebrew: "תיאטירה"},
  {name: "Sardis", hebrew: "סרדיס"},
  {name: "Philadelphia (Asia)", hebrew: "פילדלפיה"},
  {name: "Patmos", hebrew: "פתמוס"},
  {name: "Cyprus", hebrew: "קפריסין"},
  {name: "Crete", hebrew: "כרתים"},
  {name: "Malta", hebrew: "מלטה"},
  {name: "Rome", hebrew: "רומא"},
  {name: "Quirinius", hebrew: "קיריניוס"},
  {name: "Caiaphas", hebrew: "קיפא"},
  {name: "Annas", hebrew: "חנן"},
  {name: "Joseph of Arimathea", hebrew: "יוסף הרמתי"},
  {name: "Nicodemus", hebrew: "ניקודמוס"},
  {name: "Zacchaeus", hebrew: "זכאוס"},
  {name: "Bartimaeus", hebrew: "ברטימאיוס"},
  {name: "Jairus", hebrew: "יאירוס"}
];
